language: node_js

sudo: false

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "6"
  - "5"
  - "0.12"

before_script:
  - npm install
script: 
  - npm run dev
  - npm run dist